In [31]:
import pandas as pd

df = pd.read_csv('recurso.csv', sep=',')

In [220]:
df2 = pd.read_csv('recurso.csv', sep=',')

In [44]:
df

status  metodo  recurso
0          0.0     2.0    897.0
1          0.0     2.0    897.0
2          0.0     2.0    897.0
3          0.0     2.0    897.0
4          0.0     2.0    897.0
...        ...     ...      ...
472427     0.0     2.0    897.0
472437     0.0     2.0    897.0
472444     0.0     2.0    897.0
472449     0.0     2.0    897.0
472460     0.0     2.0    897.0

[455202 rows x 3 columns]

In [38]:
df = df.drop(columns=['data1'])
df = df.drop(columns=['data2'])
df = df.drop(columns=['ip'])
df = df[df.status != '-']

KeyError: "['data1'] not found in axis"

In [5]:
from sklearn import preprocessing
import numpy as np

In [39]:
enc = preprocessing.OrdinalEncoder()
status = np.expand_dims(df.status, axis=1)
status = enc.fit_transform(status)
df.status = status

In [40]:
enc = preprocessing.OrdinalEncoder()
metodo = np.expand_dims(df.metodo, axis=1)
metodo = enc.fit_transform(metodo)
df.metodo = metodo

In [41]:
enc = preprocessing.OrdinalEncoder()
recurso = np.expand_dims(df.recurso, axis=1)
recurso = enc.fit_transform(recurso)
df.recurso = recurso

In [49]:
df.groupby('recurso').count()

status  metodo
recurso                
0.0           1       1
1.0           1       1
2.0           3       3
3.0           2       2
4.0        1558    1558
...         ...     ...
1570.0        1       1
1571.0        2       2
1572.0        2       2
1573.0        1       1
1574.0        2       2

[1575 rows x 2 columns]

In [45]:
x = np.array([df.status, df.metodo, df.recurso])
x

array([[  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  2.,   2.,   2., ...,   2.,   2.,   2.],
       [897., 897., 897., ..., 897., 897., 897.]])

In [46]:
X = np.expand_dims(x, axis=0)
X

array([[[  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  2.,   2.,   2., ...,   2.,   2.,   2.],
        [897., 897., 897., ..., 897., 897., 897.]]])

In [47]:
X = np.reshape(X, (3, 455202))

In [48]:
X_normalized = preprocessing.normalize(X, norm='l2')

X_normalized

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.0013945 , 0.0013945 , 0.0013945 , ..., 0.0013945 , 0.0013945 ,
        0.0013945 ],
       [0.00188592, 0.00188592, 0.00188592, ..., 0.00188592, 0.00188592,
        0.00188592]])

In [43]:
df = df.dropna()